### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot#96]
Error while installing the bot on a new ubuntu system. libraries and python requirements installed.
```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from musicbot.telegram import bot
  File "/media/felix/Volume/git/MusicBot/musicbot/telegram/bot.py", line 14, in <module>
    from telegram.ext.messagehandler import MessageHandler, Filters
ImportError: cannot import name 'Filters'
```

**Comment by BjoernPetersen** [comment]
Filters is a part of python-telegram-bot. It was probably moved recently, I'll look into it.
