### ISSUE TITLE
Providing Device-ID

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot#97]
Error while letting the musicbot list all aviable device ID's.

Traceback:
```
No GMusic device ID found. Do you want to use this devices ID (1) or select an existing device ID (2, recommended)? 2
Enter a device ID (leave empty to show all registered devices): 
/usr/local/lib/python3.5/dist-packages/Cryptodome/Math/_Numbers_gmp.py:230: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  _gmp.gmp_snprintf(buf, c_size_t(buf_len), b("%Zd"), self._mpz_p)
14:20:53 (ERROR, music_apis.py:664): No device ID provided, printing registered devices:
14:20:53 (ERROR, music_apis.py:665): [
    {
       List of all aviable Device ID's - working and with correct information
    }
]
14:20:53 (CRITICAL, main.py:99): Error accessing GMusic. (Missing device ID in secrets)
14:20:53 (INFO, main.py:100): Maybe try offline mode (--offline argument)
14:20:53 (INFO, async_handler.py:45): Shutting down...
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    gmusic_api = music_apis.GMusicAPI()
  File "/media/***/music_apis.py", line 332, in __init__
    self._connect()
  File "/media/***/music_apis.py", line 666, in _connect
    raise ValueError("Missing device ID in secrets")
ValueError: Missing device ID in secrets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 101, in <module>
    async_handler.shutdown()
  File "/media/***/async_handler.py", line 48, in shutdown
    os.kill(os.getpid(), signal.SIGINT)
KeyboardInterrupt
```

**Comment by BjoernPetersen** [comment]
Seems like you interrupted the shutdown process by hitting Ctrl+C.
Apart from this, shutting down after printing devices is expected behavior right now.

**Comment by FelixGail** [comment]
I did not, but if the process should shutdown anyway this works for me.
The device-ids are listed as error, though. Wouldn't it be better to list them and call sys.exit() manually instead of letting the program run into an critical error?

**Comment by BjoernPetersen** [comment]
Probably...
That doesn't have a high priority right now though.

**Comment by BjoernPetersen** [comment]
Followup issue: #100
